display_name: Patterns
description: Clarity for the mind through structured reflection.
maintainer:
  name: maskedsyntax
  email: aftaab@aftaab.xyz
license: MIT
url: https://github.com/maskedsyntax/patterns
packager: maskedsyntax
groups:
  - productivity
